<a href="https://colab.research.google.com/github/taisriquinho/Curso-Machine-Learning-/blob/main/01-Explorando-conjunto-de-dados/Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s.values

array([1, 2, 3, 4, 5])

In [ ]:
s = pd.Series([15,20,12,16,10,11,12,15,9,10,12,17], index = ['jan','fev', 'mar','abr', 'mai', 'jun','jul', 'ago', 'set','out','nov', 'dez'])
s

jan    15
fev    20
mar    12
abr    16
mai    10
jun    11
jul    12
ago    15
set     9
out    10
nov    12
dez    17
dtype: int64

In [ ]:
s['nov']

np.int64(12)

In [ ]:
s[0:6]

jan    15
fev    20
mar    12
abr    16
mai    10
jun    11
dtype: int64

In [ ]:
s.mean() #média

np.float64(13.25)

In [ ]:
s.std() #desvio padrão

3.333712099692528

In [ ]:
s.max() #valor máximo

20

In [ ]:
s.min() #valor mínimo

9

In [ ]:
s.describe()

count    12.000000
mean     13.250000
std       3.333712
min       9.000000
25%      10.750000
50%      12.000000
75%      15.250000
max      20.000000
dtype: float64

In [ ]:
s.sum()

np.int64(159)

In [ ]:
s[6:].mean() #média dos últimos 6 meses

np.float64(12.5)